### ISSUE TITLE
Server crashing with "Application error: a server-side exception has occurred (see the server logs for more information). Digest: 1802768317"

### ISSUE THREAD

**Issue by she0305** [calcom/platform-starter-kit#34] opened 2024-07-03 01:23 UTC
### Description
I'm using Supabase + Cal.com platform-starter-kit and deploying with Vercel. My server crashes very frequently with "Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1802768317". I'm pretty new to this, and just got the cal.com Platform product. Can someone help me with this issue?

<img width="1504" alt="image" src="https://github.com/calcom/platform-starter-kit/assets/95587111/3f126a28-03ac-4ae8-8168-169ed8450418">

Server log: 
```
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "08P01", message: "bind message supplies 3 parameters, but prepared statement \"s12\" requires 1", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at In.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client/runtime/library.js:122:7067)
    at In.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/var/task/node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client/runtime/library.js:127:11167) {
  clientVersion: '5.15.0',
  digest: '1802768317'
}
```
I'm not sure if this is relevant, but I haven't been able to seed with the given Supabase seed.sql file as well.. 
<img width="707" alt="image" src="https://github.com/calcom/platform-starter-kit/assets/95587111/9e78f0b6-ed5d-46b4-961a-c5807bf250af">

**Comment by p6l-richard** [comment] 2024-07-12 17:13
There are two errors here in this issue.
1. The seeding script doesn't work (requirement for app to work)
2. Prisma throwing a `ConnectorError`

---

### Seeding script

**Problem**

- This error occurred because the database table wasn't seeded with the `FilterOption` rows.
- The root cause here were were duplicate `FilterOption`s ("consultant") leading to the creation to throw an error. 

**Solution**

[This PR](https://github.com/calcom/platform-starter-kit/pull/35) will change the seed script, so that:
- allows for easier debugging
  - previously, when the script only partially failed, there were no logs of the last successful step
  - now, it logs each successfully inserted filter to understand where the point of failure occurred
- allows re-using the seeding script
  - previously, when the seeding script didn't failed after some successfil insertions on the first attempt, it wouldn't work in a second attempt
  - now, it can be re-used and will clean up previous executions
  
  
### Prisma's `ConnectorError`
Presumably, it has to do with the connection pooling management from our ORM solution Prisma in combination with supabase's pgbouncer connection string ([`POSTGRES_PRISMA_URL`](https://github.com/calcom/examples/blob/a7c19253e77dd14523054e98dbe5706ecc6f80c6/.env.example#L14) to postgres. 

From some issues on prisma's repo, there seem to be two potential fixes:

1. Restart supabase project if connected without `?pgbouncer=true` even once
[Source](https://github.com/prisma/prisma/issues/11643#issuecomment-1268341203)

2. Omit `?pgbouncer=true` entirely 
[Source](https://github.com/prisma/prisma/discussions/22837#discussioncomment-8305078)


---

@she0305  can you try both of these fixes? If the issue persists with each of these, you can file a discussion on Prisma [here](https://github.com/prisma/prisma/discussions)?

**Comment by p6l-richard** [comment] 2024-07-22 13:00
Closing this as the error appears to be resolved with [these fixes](https://github.com/calcom/platform-starter-kit/issues/34#issuecomment-2225993844) on the user's implementation.

If you encounter a similar or related error, feel free to open a new issue.

**Closed as completed by p6l-richard** 2024-07-22 13:00 UTC

**Comment by she0305** [comment] 2024-07-23 23:53
I can confirm that the Prisma error was fixed with the presented solution. 
However, the server error is caused by the bug deleting the user that Cal.com team is aware of and will investigate. 

----
### Description 
If admin tries to delete a user from the Supabase database, and the user tries to create an account with the same information, the server crashes. The (recreated) user does not have Cal.com token properly populated. Seems like there is a disconnection in deleting user workflow between the Supabase database and the cal.com-managed user database.
